config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  authenticated :user do
    root to: 'products#index', as: :authenticated
  end

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :products, only: %i[index show]
  resources :tickets, only: %i[new create]

  get :autocomplete, to: 'products#autocomplete'
  get :search, to: 'products#search'

  authenticate :user do
    get :cart,            to: 'carts#show'
    get :profile,         to: 'users#profile'
    put :update_profile,  to: 'users#update_profile'

    resources :cart_items, only: %i[create destroy]
    resources :products, only: %i[] do
      resources :reviews, only: %i[create destroy update], shallow: true
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  COUNTRY_CODES = ISO3166::Country.codes
  EMAIL_REGEX   = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  mount_uploader :avatar, AvatarUploader

  has_one :cart, dependent: :destroy
  has_many :cart_items, through: :cart
  has_many :reviews, dependent: :destroy
  has_many :tickets

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         authentication_keys: [:login]

  validates :name, length: { in: 4..25 }, uniqueness: true
  validates :email, format: { with: EMAIL_REGEX }
  validates :country, allow_blank: true, inclusion:
  { in: COUNTRY_CODES, message: '%{value} is not a valid Country Code' }
  validates :city, :street, length: { in: 3..50 }, allow_blank: true
  validates :post_code, zipcode: { country_code_attribute: :country },
                        allow_blank: true
  validates :phone_number, format: { with: /(?:\+?|\b)[0-9]{10}\b/ },
                           length: { in: 12..15 }, allow_blank: true
  validates :credit_card_number, length: { in: 9..25 }, allow_blank: true
  validates :credit_card_sec, length: { is: 3 }, allow_blank: true
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  attr_accessor :login

  # overwrite Devise authentication - allow login using email or name
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h)
        .find_by(['lower(name) = :value OR lower(email) = :value',
                  { value: login.downcase }])
    elsif conditions.key?(:name) || conditions.key?(:email)
      find_by conditions.to_h
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  def profile
    @resource = current_user
  end

  def update_profile
    @resource = current_user
    if @resource.update_attributes profile_params
      redirect_to :profile, notice: 'Profile updated'
    else
      render :profile
    end
  end

  private

  def profile_params
    params.require(:user).permit(:country, :city, :street, :post_code,
                                 :phone_number, :credit_card_number,
                                 :credit_card_sec, :exp_date)
  end
end

app/views/users/profile.html.erb
<div class="container profile">
  <div class="col-sm-6 col-sm-offset-3">
    <div class="panel panel-default panel-body">
      <h3>Edit Contact Info</h3>

      <%= form_for(resource, as: resource_name, url: update_profile_path(resource), html: { method: :put }) do |f| %>


          <div class="field form-group">
            <%= f.label :country, class: 'control-label' %>
            <!-- <%= f.text_field :country, class: 'form-control' %> -->
            <%= f.country_select :country, { selected: resource.country, include_blank: 'Select a Country' }, { class: 'form-control' } %>
          </div>

          <div class="field form-group">
            <%= f.label :city, class: 'control-label' %><br />
            <%= f.text_field :city, class: 'form-control' %>
          </div>

          <div class="field form-group">
            <%= f.label :street, class: 'control-label' %><br />
            <%= f.text_field :street, autocomplete: 'off', class: 'form-control' %>
          </div>

          <div class="field form-group">
            <%= f.label :post_code, class: 'control-label' %><br />
            <%= f.text_field :post_code, class: 'form-control' %>
          </div>

          <div class="field form-group">
            <%= f.label :phone_number, class: 'control-label' %><br />
            <%= f.text_field :phone_number, class: 'form-control' %>
            <span class="help-block">For example +48531969029</span>
          </div>

          <div class="panel panel-warning panel-credit-card panel-collapsed">
            <div class="panel-heading clickable" data-toggle="tooltip"
            data-placement="right" title="Careful! Sensitive data">
              <h3 class="panel-title">
                Credit Card Info
                <i class="fa fa-chevron-down pull-right" aria-hidden="true"></i>
              </h3>
            </div>
            <div class="panel-body">
              <div class="field form-group">
                <%= f.label :credit_card_number, class: 'control-label' %><br />
                <%= f.text_field :credit_card_number, class: 'form-control' %>
              </div>

              <div class="field form-group">
                <%= f.label 'Security Code',class: 'control-label' %><br />
                <%= f.text_field :credit_card_sec, class: 'form-control' %>
              </div>

              <div class="field form-group">
                <%= f.label 'Expiry Date', class: 'control-label' %><br />
                <%= f.text_field :exp_date, class: 'form-control' %>
              </div>
            </div>
          </div>

          <div class="actions form-group">
            <%= f.submit 'Update', class: 'btn btn-success pull-right' %>
          </div>
      <% end %>
    </div>
  </div>
</div>