config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  authenticated :user do
    root to: 'products#index', as: :authenticated
  end

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :products, only: %i[index show]
  resources :tickets, only: %i[new create]

  get :autocomplete, to: 'products#autocomplete'
  get :search, to: 'products#search'

  authenticate :user do
    get :cart,            to: 'carts#show'
    get :profile,         to: 'users#profile'
    put :update_profile,  to: 'users#update_profile'

    resources :cart_items, only: %i[create destroy]
    resources :products, only: %i[] do
      resources :reviews, only: %i[create destroy update], shallow: true
    end
  end
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @cart = Cart.find_by(user: current_user)

    @cart ||= current_user.create_cart

    @cart_items = @cart.cart_items.includes(:product)
    @users = User.all
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/views/carts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-7 col-sm-offset-1">
      <div class="panel panel-default panel-body">
        <table class="table">
          <thead>
            <tr>
              <th>Product</th>
              <th><span class="pull-right">Price</span></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @cart_items.each do |item| %>
              <tr>
                <td class="col-sm-5"><%= item.product.name %></td>
                <td class="col-sm-5"><span class="pull-right"><%= item.product.price %> $</span></td>
                <td class="col-sm-2">
                  <%= link_to cart_item_path(item), method: :delete do %>
                    <i class="fa fa-trash fa-lg pull-right" aria-hidden="true"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      </div>
    <div class="col-sm-4 cart-summary">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="col-sm-4">
            <%= pluralize(@cart_items.count, 'product') %>
          </div>
          <div class="col-sm-5 col-sm-offset-3">
            <span class="pull-right">
              <%= @cart_items.sum(:price) %> $
            </span>
          </div>

          <div class="col-sm-4">
            <span>shipping:</span>
          </div>
          <div class="col-sm-5 col-sm-offset-3">
           <span class="pull-right">free</span>
          </div>
        </div>
        
        <div class="panel-footer cart-sum">
          <div class="col-sm-4">
            <b>Sum:</b>
          </div>
          <div class="col-sm-5 col-sm-offset-3">
           <b class="pull-right">
             <%= @cart_items.sum(:price) + 10 %> $
           </b>
          </div>
          <div class="clearfix checkout">
            <%= link_to 'Checkout', '#', class: 'btn btn-success pull-right' %>
          </div>
        </div>


      </div>
    </div>
  </div>
</div>