config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  authenticated :user do
    root to: 'products#index', as: :authenticated
  end

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :products, only: %i[index show]
  resources :tickets, only: %i[new create]

  get :autocomplete, to: 'products#autocomplete'
  get :search, to: 'products#search'

  authenticate :user do
    get :cart,            to: 'carts#show'
    get :profile,         to: 'users#profile'
    put :update_profile,  to: 'users#update_profile'

    resources :cart_items, only: %i[create destroy]
    resources :products, only: %i[] do
      resources :reviews, only: %i[create destroy update], shallow: true
    end
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :categorizations
  has_many :categories, through: :categorizations
  has_many :reviews, dependent: :destroy
  has_many :pictures, dependent: :destroy, inverse_of: :product
  accepts_nested_attributes_for :pictures, allow_destroy: true

  validates :name, length: { in: 4..25 }, uniqueness: true
  validates :description, length: { in: 4..500 }
  validates :price, numericality: { greater_than_or_equal_to: 1.0 }
  validates :pictures, length: { maximum: 5 }
  validate :validate_categories

  after_save :set_default_picture, if: (proc do |product|
    product.pictures.blank?
  end)

  def calculate_average_rating
    ratings = reviews.pluck(:rating)
    avg = ratings.inject { |sum, el| sum + el }.to_f / ratings.size
    self.rating_cache = avg.round(1)
    self.review_count = reviews.count
    save!
  end

  def images
    pictures.map(&:file)
  end

  def image
    images.first
  end

  def self.autocomplete_json(query)
    where("lower(name) like ?", "%#{query}%")
    .select(:name, :id).collect do |product|
      {
        value: product.name,
        data: product.id
      }
    end.to_json
  end

  private

  def validate_categories
    message = 'too many (You can only select 3)'
    errors.add(:categories, message) if categories.size > 3
  end

  def set_default_picture
    picture = pictures.build
    picture.save
  end

  def invalid_file?(attributes)
    attributes['filename'].blank? and attributes['filename_cache'].blank?
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.order('created_at DESC')
                       .includes(:categories, :pictures)
                       .paginate(page: params[:page], per_page: 9)
  end

  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews.includes(:user)
                       .paginate(page: params[:page], per_page: 6)
  end

  def autocomplete
    render json: Product.autocomplete_json(params[:query].downcase)
  end

  def search
    # TODO: move logic to model
    term = params[:query].downcase

    @products = Product.includes(:pictures, :categorizations)
                       .eager_load(:categories)
    @products = @products.where("lower(products.name) LIKE ?", "%#{term}%") if term
    if params[:categories]
      categories_ids = params[:categories].values.map(&:to_i)
      @products = @products.where("categories.id IN (?)", categories_ids)
    end

    @products = @products.order(created_at: :desc)
                         .paginate(page: params[:page], per_page: 9)

    render :index
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/products/_product.html.erb
<%# frozen_string_literal: true %>
<div class="col-sm-4 product">
  <div class="thumbnail" >
    <%= link_to product_path(product) do %>
        <%= image_tag product.image.url(:medium), class: 'product-thumbnail' %>
        <div class="row product-header">
          <div class="col-sm-9 name-container">
            <h3 class="product-name"><%= product.name %></h3>
          </div>
          <div class="col-sm-3 price">
            <h3>
              <label class="">$<%= product.price %></label>
            </h3>
          </div>
        </div>
      <% end %>
      <div class="description">
        <%= truncate product.description, length: 180 %>
      </div>
      <div class="categories-links">
        <% product.categories.each do |category| %>
          <%= link_to category.name, '#', class: 'small-link' %>
        <% end %>
      </div>
      <%= link_to cart_items_path(product_id: product.id), method: :post, class: 'btn btn-info btn-add-to-cart' do %>
        <span class="fa fa-shopping-cart"></span> Add to Cart
      <% end %>
  </div>
</div>

app/views/products/index.html.erb
<%# frozen_string_literal: true %>
<div class="container products">
    <%= render @products %>
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <%= will_paginate(@products) %>
      </div>
    </div>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="card col-md-10 col-md-offset-1">
    <div class="container-fluid">
      <div class="wrapper row-">
        <div class="preview col-md-6">

          <div class="preview-pic tab-content">
            <% @product.images.each.with_index(1) do |image, i| %>
              <div class="tab-pane <%= i==1 ? 'active' : '' %>" id="pic-<%=i%>">
                <%= image_tag image.url(:medium), size: "400x252" %>
              </div>
            <% end %>
          </div>

          <div class="table">
            <ul class="preview-thumbnail nav nav-tabs">
              <% @product.images.each.with_index(1) do |image, i| %>
                <li class="<%= i==1 ? 'active' : '' %>">
                  <a data-target="#pic-<%=i%>" data-toggle="tab">
                    <%= image_tag image.url(:medium), size: "200x126" %>
                  </a>
                </li>
              <% end %>
            </ul>
          </div>


        </div>

        <div class="details col-md-6">
          <h3 class="product-title">
            <%= @product.name %>
          </h3>
          <div class="rating">
            <div class="stars">
              <%= select_tag :product, options_for_select(1..5, 3), class: 'avg-rating', 'data-rating-cache': @product.rating_cache %>
            </div>
            <span class="review-no">
              <%= pluralize(@product.review_count, 'review') %>
            </span>
          </div>
          <p class="product-description">
            <%= @product.description %>
          </p>
          <h4 class="price">
            current price: <span><%= @product.price %> $</span>
          </h4>
          <p class="vote"><strong>91%</strong> of buyers enjoyed this product! <strong>(87 votes)</strong></p>
          <!-- <h5 class="sizes">sizes:
            <span class="size" data-toggle="tooltip" title="small">s</span>
            <span class="size" data-toggle="tooltip" title="medium">m</span>
            <span class="size" data-toggle="tooltip" title="large">l</span>
            <span class="size" data-toggle="tooltip" title="xtra large">xl</span>
          </h5>
          <h5 class="colors">colors:
            <span class="color orange not-available" data-toggle="tooltip" title="Not In store"></span>
            <span class="color green"></span>
            <span class="color blue"></span>
          </h5> -->
          <div class="action">
            <button class="add-to-cart btn btn-default" type="button">add to cart</button>
            <button class="like btn btn-default" type="button"><span class="fa fa-heart"></span></button>
          </div>
        </div>
      </div>
    </div>
  </div>
    <div class="row col-md-6 col-md-offset-3 product-reviews">
      <%= form_for Review.new, url: product_reviews_path(@product), method: :post  do |f| %>
        <div class="form-group">
          <%= f.text_area :comment, class: 'form-control' %>
        </div>

        <div class="form-group review-rate-select">
          <%= f.select :rating, 1..5 %>
        </div>

        <div class="form-group">
          <%= f.submit 'Add Review', class: 'form-control btn btn-info' %>
        </div>
      <% end %>

      <% @reviews.each do |review| %>
        <%= render review %>
      <% end %>

      <%= will_paginate @reviews %>
  </div>
</div>