config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  authenticated :user do
    root to: 'products#index', as: :authenticated
  end

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :products, only: %i[index show]
  resources :tickets, only: %i[new create]

  get :autocomplete, to: 'products#autocomplete'
  get :search, to: 'products#search'

  authenticate :user do
    get :cart,            to: 'carts#show'
    get :profile,         to: 'users#profile'
    put :update_profile,  to: 'users#update_profile'

    resources :cart_items, only: %i[create destroy]
    resources :products, only: %i[] do
      resources :reviews, only: %i[create destroy update], shallow: true
    end
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    can :read, [CartItem, Product]
    can :create, [CartItem, Review]
    can %i[destroy update], Review, user_id: user.id
    can :destroy, CartItem, cart: { user_id: user.id }
  end
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
end

app/models/cart_item.rb
# frozen_string_literal: true

class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/categorization.rb
# frozen_string_literal: true

class Categorization < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  # has_and_belongs_to_many :products, join_table: :categories_products
  has_many :categorizations
  has_many :categories, through: :categorizations
end

app/models/picture.rb
# frozen_string_literal: true

class Picture < ApplicationRecord
  belongs_to :product, inverse_of: :pictures

  mount_uploader :file, FileUploader

  validates :product, presence: true
  validate :file_size_validation
  validates_integrity_of :file
  validates_processing_of :file

  private

  def file_size_validation
    errors[:file] << "should be less than 5MB" if file.size > 5.megabytes
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :categorizations
  has_many :categories, through: :categorizations
  has_many :reviews, dependent: :destroy
  has_many :pictures, dependent: :destroy, inverse_of: :product
  accepts_nested_attributes_for :pictures, allow_destroy: true

  validates :name, length: { in: 4..25 }, uniqueness: true
  validates :description, length: { in: 4..500 }
  validates :price, numericality: { greater_than_or_equal_to: 1.0 }
  validates :pictures, length: { maximum: 5 }
  validate :validate_categories

  after_save :set_default_picture, if: (proc do |product|
    product.pictures.blank?
  end)

  def calculate_average_rating
    ratings = reviews.pluck(:rating)
    avg = ratings.inject { |sum, el| sum + el }.to_f / ratings.size
    self.rating_cache = avg.round(1)
    self.review_count = reviews.count
    save!
  end

  def images
    pictures.map(&:file)
  end

  def image
    images.first
  end

  def self.autocomplete_json(query)
    where("lower(name) like ?", "%#{query}%")
    .select(:name, :id).collect do |product|
      {
        value: product.name,
        data: product.id
      }
    end.to_json
  end

  private

  def validate_categories
    message = 'too many (You can only select 3)'
    errors.add(:categories, message) if categories.size > 3
  end

  def set_default_picture
    picture = pictures.build
    picture.save
  end

  def invalid_file?(attributes)
    attributes['filename'].blank? and attributes['filename_cache'].blank?
  end
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
  after_create :recalculate_cache
  after_destroy :recalculate_cache

  validates :comment, length: { in: 4..255 }
  validates :rating, numericality: { only_integer: true,
                                     greater_than_or_equal_to: 1,
                                     less_than_or_equal_to: 5 }

  private

  def recalculate_cache
    product.calculate_average_rating
  end
end

app/models/ticket.rb
# frozen_string_literal: true

class Ticket < ApplicationRecord
  # TODO: eliminate EMAIL REGEX duplication
  EMAIL_REGEX   = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  belongs_to :user

  validates :content, length: { in: 6..1000 }
  validates :name, length: { in: 4..25 }
  validates :email, format: { with: EMAIL_REGEX }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  COUNTRY_CODES = ISO3166::Country.codes
  EMAIL_REGEX   = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  mount_uploader :avatar, AvatarUploader

  has_one :cart, dependent: :destroy
  has_many :cart_items, through: :cart
  has_many :reviews, dependent: :destroy
  has_many :tickets

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         authentication_keys: [:login]

  validates :name, length: { in: 4..25 }, uniqueness: true
  validates :email, format: { with: EMAIL_REGEX }
  validates :country, allow_blank: true, inclusion:
  { in: COUNTRY_CODES, message: '%{value} is not a valid Country Code' }
  validates :city, :street, length: { in: 3..50 }, allow_blank: true
  validates :post_code, zipcode: { country_code_attribute: :country },
                        allow_blank: true
  validates :phone_number, format: { with: /(?:\+?|\b)[0-9]{10}\b/ },
                           length: { in: 12..15 }, allow_blank: true
  validates :credit_card_number, length: { in: 9..25 }, allow_blank: true
  validates :credit_card_sec, length: { is: 3 }, allow_blank: true
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  attr_accessor :login

  # overwrite Devise authentication - allow login using email or name
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h)
        .find_by(['lower(name) = :value OR lower(email) = :value',
                  { value: login.downcase }])
    elsif conditions.key?(:name) || conditions.key?(:email)
      find_by conditions.to_h
    end
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @cart = Cart.find_by(user: current_user)

    @cart ||= current_user.create_cart

    @cart_items = @cart.cart_items.includes(:product)
    @users = User.all
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  def profile
    @resource = current_user
  end

  def update_profile
    @resource = current_user
    if @resource.update_attributes profile_params
      redirect_to :profile, notice: 'Profile updated'
    else
      render :profile
    end
  end

  private

  def profile_params
    params.require(:user).permit(:country, :city, :street, :post_code,
                                 :phone_number, :credit_card_number,
                                 :credit_card_sec, :exp_date)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def resource
    @resource ||= User.new
  end

  def resource_name
    resource.class.name.downcase.to_sym
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[resource_name]
  end
end

app/helpers/cart_items_helper.rb
# frozen_string_literal: true

module CartItemsHelper
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def default_value(input:)
    return '' unless current_user

    case input
      when :name then current_user.name
      when :email then current_user.email
      else ''
    end
  end
end

app/views/layouts/_alerts.html.erb
<%# frozen_string_literal: true %>
<div id="alerts">
  <% if flash[:notice] %>
      <div class="alert notice alert-info alert-dismissable fade in">
        <span href="#" class="close" data-dismiss="alert" aria-label="close">&times;</span>
        <%= notice %>
      </div>
  <% elsif flash[:alert] %>
      <div class="alert alert-danger alert-dismissable fade in">
        <span href="#" class="close" data-dismiss="alert" aria-label="close">&times;</span>
        <%= alert %>
      </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<!-- <div class="navbar navbar-default navbar-bottom">
  <div class="container-fluid">
    <p class="navbar-text pull-left">© 2014 - Site Built By Mr. M.
         <a href="http://tinyurl.com/tbvalid" target="_blank" >HTML 5 Validation</a>
    </p>

    <a href="http://youtu.be/zJahlKPCL9g" class="navbar-btn btn-danger btn pull-right">
    <span></span>  Subscribe on YouTube</a>
  </div>
</div> -->

<div class="navbar navbar-default footer">
  <div class="container-fluid">
    <p class="navbar-text pull-left">© 2017 - Site Built By Jakub Kopyś
         <a href="http://tinyurl.com/tbvalid" target="_blank" >HTML 5 Validation</a>
    </p>

    <%= link_to "Contact Us", "#", class: 'navbar-btn btn btn-default' %>
    <%= link_to "About Us", "#", class: 'navbar-btn btn btn-default' %>
    <%= link_to "FAQ", "#", class: 'navbar-btn btn btn-default' %>


    <a href="http://youtu.be/zJahlKPCL9g" class="navbar-btn btn-danger btn pull-right">
    <span></span>  Subscribe on YouTube</a>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <%= image_tag("shield.png", height: '40', style: 'margin-top: -10px;') %>
      </a>
    </div>
    <div class="collapse navbar-collapse" id="navbar">
      <%= form_tag('/search', method: 'GET', class: 'navbar-form navbar-left') do %>
        <div class="input-group">
          <%= text_field_tag :query, '', class: 'form-control', id: 'search', placeholder: 'Search' %>
          <div class="hide">
            <% @categories.each do |category| %>
              <div class="checkbox">
                <label><%= check_box_tag "categories[#{category.name}]", category.id.to_s, false, id: "checkbox-#{category.id}-form" %>Option</label>
              </div>
            <% end %>
          </div>
          <div class="input-group-btn">
            <%= button_tag type: 'submit', class: 'btn btn-default' do %>
              <i class="fa fa-search" aria-hidden="true"></i>
            <% end %>
          </div>
        </div>
      <% end %>
      <button class="btn btn-default navbar-btn" data-toggle="popover" data-placement="bottom" data-container="body" data-html="true">
        Categories <i class="fa fa-caret-down" aria-hidden="true"></i>
      </button>
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
          <li>
            <%= link_to new_user_session_path do %>
              Sign In <i class="fa fa-sign-in fa-lg" aria-hidden="true"></i>
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path do %>
              Register <i class="fa fa-user-plus fa-lg" aria-hidden="true"></i>
            <% end %>
          </li>
          <li>
            <!-- Trigger the modal with a button -->
            <%= link_to '#', data: {'toggle': 'modal', 'target': "#modal-ticket", 'placement': 'right'}, title: 'Submit ticket' do %>
              Support <i class="fa fa-question fa-lg" aria-hidden="true"></i>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to products_path do %>
              Home <i class="fa fa-home fa-lg" aria-hidden="true"></i>
            <% end %>
          </li>
          <li>
            <%= link_to cart_path do %>
              Cart <i class="fa fa-shopping-cart fa-lg" aria-hidden="true"></i>
              <span class="label label-pill label-info"><%= current_user.cart_items.count %></span>
            <% end %>
          </li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", data: { toggle: "dropdown" } do %>
              <%= current_user.name %> <i class="fa fa-user fa-lg" aria-hidden="true"></i>
              <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu">
              <li>
                <%= link_to profile_path do %>
                  Profile <i class="fa fa-address-card-o pull-right" aria-hidden="true"></i>
                <% end %>
              </li>
              <li>
                <%= link_to edit_user_registration_path do %>
                  Account <i class="fa fa-cogs pull-right" aria-hidden="true"></i>
                <% end %>
              </li>
            </ul>
          </li>
          <li>
            <!-- Trigger the modal with a button -->
            <%= link_to '#', data: {'toggle': 'modal', 'target': "#modal-ticket", 'placement': 'right'}, title: 'Submit ticket' do %>
              Support <i class="fa fa-question fa-lg" aria-hidden="true"></i>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: 'DELETE' do %>
              Sign out <i class="fa fa-sign-out fa-lg" aria-hidden="true"></i>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<%= render '/modals/ticket' %>
<%= render '/categories/filters_popover', categories: @categories %>

app/views/layouts/application.html.erb
<%# frozen_string_literal: true %>
<!DOCTYPE html>
<html>
  <head>
    <title>RailsShop</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="content">

    <%= render 'layouts/nav' unless @disable_header %>
    <% if flash.any? %>
      <%= render 'layouts/alerts' %>
    <% end %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/modals/_edit_review.html.erb
<div class="modal fade" id="modal-<%=review.id%>" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Edit Review</h4>
      </div>
      <div class="modal-body">
        <%= form_for review, method: :put  do |f| %>
          <div class="form-group">
            <%= f.text_area :comment, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.select :rating, 1..5, {}, class: 'modal-review-rating' %>
          </div>

          <div class="form-group">
            <%= f.submit 'Submit', class: 'form-control btn btn-info' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/modals/_ticket.html.erb
<div class="modal fade" id="modal-ticket" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Submit Support Ticket</h4>
      </div>
      <div class="modal-body">
        <%= form_for Ticket.new, method: :post  do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control', required: true, value: default_value(input: :name) %>
          </div>

          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control', required: true, value: default_value(input: :email) %>
          </div>

          <div class="form-group">
            <%= f.label :content %>
            <%= f.text_area :content, class: 'form-control', required: true %>
          </div>

          <div class="form-group">
            <%= f.submit 'Submit', class: 'form-control btn btn-info' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>